version: '3.8'

services:
  # 后端服务
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: tinyai-search-backend
    restart: always
    image: tinyai-search-backend:v1.0.0
    network_mode: "host"  # 使用主机网络
    environment:
      # 后端运行端口
      - PORT=8000
    volumes:
      # 挂载数据库文件到宿主机，确保数据持久化
      - ./chat_history_docker.db:/app/chat_history_docker.db
      - ./config_docker.db:/app/config_docker.db
      - ./docker_logs:/app/logs

  # 前端服务
  frontend:
    build:
      context: ./frontend
      dockerfile: frontend.Dockerfile
    container_name: tinyai-search-frontend
    restart: always
    image: tinyai-search-frontend:v1.0.0
    network_mode: "host"  # 使用主机网络
    environment:
      - PORT=3000

  # Nginx 反向代理服务
  nginx-proxy:
    image: nginx:stable-alpine
    container_name: tinyai-nginx-proxy
    restart: always
    network_mode: "host"  # 使用主机网络
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro 
    depends_on:
      - backend
      - frontend

