version: '3.8'

services:
  # 后端服务
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: tinyai-search-backend
    restart: always
    image: tinyai-search-backend:v1.0.0
    volumes:
      # 挂载数据库文件到宿主机，确保数据持久化
      - ./chat_history_docker.db:/app/chat_history_docker.db
      - ./config_docker.db:/app/config_docker.db
      - ./docker_logs:/app/logs
    networks: 
      - my-network

  # 前端服务
  frontend:
    build:
      context: ./frontend
      dockerfile: frontend.Dockerfile
    container_name: tinyai-search-frontend
    restart: always
    image: tinyai-search-frontend:v1.0.0
    networks:
      - my-network

  # Nginx 反向代理服务
  nginx-proxy:
    image: nginx:stable-alpine
    container_name: tinyai-nginx-proxy
    restart: always
    ports:
      - "8080:80" # 将主机的 8080 端口映射到容器的 80 端口
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro 
    depends_on:
      - backend
      - frontend
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
